// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn4QfVfM66tC3zFRPCATQ1BAx_ZseHdLI',
    appId: '1:839067287740:web:b40dc108438db5763c50b9',
    messagingSenderId: '839067287740',
    projectId: 'pocketfine-finance-tracker',
    authDomain: 'pocketfine-finance-tracker.firebaseapp.com',
    storageBucket: 'pocketfine-finance-tracker.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD76AsPACjrWyRsL391N75qujrXRKSiiTM',
    appId: '1:839067287740:android:4105990ebfae7a6b3c50b9',
    messagingSenderId: '839067287740',
    projectId: 'pocketfine-finance-tracker',
    storageBucket: 'pocketfine-finance-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-1iLidiJTtJ65DY9mcbli0_R4kW6wExg',
    appId: '1:839067287740:ios:61cd66950fa5fabe3c50b9',
    messagingSenderId: '839067287740',
    projectId: 'pocketfine-finance-tracker',
    storageBucket: 'pocketfine-finance-tracker.firebasestorage.app',
    iosBundleId: 'com.example.pocketfineFinanceTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-1iLidiJTtJ65DY9mcbli0_R4kW6wExg',
    appId: '1:839067287740:ios:61cd66950fa5fabe3c50b9',
    messagingSenderId: '839067287740',
    projectId: 'pocketfine-finance-tracker',
    storageBucket: 'pocketfine-finance-tracker.firebasestorage.app',
    iosBundleId: 'com.example.pocketfineFinanceTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn4QfVfM66tC3zFRPCATQ1BAx_ZseHdLI',
    appId: '1:839067287740:web:a43ab680b90156e23c50b9',
    messagingSenderId: '839067287740',
    projectId: 'pocketfine-finance-tracker',
    authDomain: 'pocketfine-finance-tracker.firebaseapp.com',
    storageBucket: 'pocketfine-finance-tracker.firebasestorage.app',
  );
}
